### ISSUE TITLE
itools export-eurostag network reader

### ISSUE THREAD

**Issue by nomont** [itesla/ipst#133]
The itools export-eurostag command reads network files without using the loader so that it is necessary to unzip grid files.
It should be harmonized with the others.

**Comment by CBiasuzzi** [comment]
.... export-eurostag has been 'harmonized' ,  example: 
./itools export-eurostag --case-file ./20130115_1845_SN2_FR0.zip --output-dir ./out

**Comment by nomont** [comment]
It works, but it is now impossible to read uncompressed CIM data (because 3 files should be read). It would be nice that the reader understands that basename_EQ.xml involves that the other 2 files are also present.

**Comment by mathbagu** [comment]
The initial issue doesn't exist anymore. Import uncompressed CIM files bug should be solved in its own issue (#196)
