### ISSUE TITLE
Forbidden characters in eurostag equipment names

### ISSUE THREAD

**Issue by mathbagu** [itesla/ipst#220]
There is a list of forbidden characters in eurostag equipment names. These characters have to be replaced by all the EurostagNamingStrategy implementation classes.
The list of these characters (we don't have an exhaustive list...) and the replacement character should be configurable.

Here is the list of known forbidden characters: / % ( ) ^ $ , ; ? 
Here is the list of known authorized characters: @ # £ µ * ! & " | ` \  [ ] { } ¨  ¤ § : < > + = ° ‘ ²

**Comment by CBiasuzzi** [comment]
are you suggesting to map and replace each character in the forbidden characters set with one of the second list?  is it what you mean by 'authorized characters' ? (otherwise an exhaustive authorized set of  chars should include  [0..9a..zA..Z], I guess )

**Comment by mathbagu** [comment]
The authorized characters list is given for information only, and you right, to be exhaustive, it also contains alpha-numerical characters.
If you pick one character in this list as a default replacement character, it should work.

**Comment by mathbagu** [comment]
See #229
