### ISSUE TITLE
OnlineWorkflowParameters adjustment

### ISSUE THREAD

**Issue by mathbagu** [itesla/ipst#97]
The countries parameter should be required.
The caseType parameter should be required.

Refactor these statements
```
        Set<SecurityIndexType> securityIndexes = null;
        String securityIndexesAsString = config.getStringProperty("securityIndexes", "");
        if ( !"".equals(securityIndexesAsString) ) {
            securityIndexes = Arrays.stream(securityIndexesAsString.split(","))
                    .map(SecurityIndexType::valueOf)
                    .collect(Collectors.toSet());
        }
```
by
```
        Set<SecurityIndexType> securityIndexes = getEnumSetProperty("securityIndexes", SecurityIndexType.class, null);
```

**Comment by mathbagu** [comment]
It seems we didn't understand. When I wrote "The countries and the caseType parameters should be required", I'd like to say that these parameters should not have a hard-coded default value. There is no good reason to set the default value to countries=FR and caseType=FO.
Could you fix it?

**Comment by CBiasuzzi** [comment]
... project iTesla's heritage, again:  online WFs were supposed to be run on FOs, by default.
Ok, I'm going to remove those defaults.
